### ISSUE TITLE
Implement toast service with planned style.

### ISSUE THREAD

**Issue by Niklas-Seppala** [Niklas-Seppala/SpotifyMap#18]

**Comment by Paattis** [comment]
Example from Figma prototype, the toast message is visible at the top
![image](https://user-images.githubusercontent.com/11006492/164190680-f128c7dd-70bf-4a16-9fac-923fa97059a8.png)

**Comment by Paattis** [comment]
We can use the [Toast-Swift](https://github.com/scalessec/Toast-Swift) library to provide the Toast since it supports styles etc.

**Comment by Paattis** [comment]
Luckily [PopupView](https://github.com/exyte/PopupView) exists
